site:
  siteIcon: /img/avatar.webp #站点图标
  avatar: /img/avatar.webp #站点头像
  name: Rootlex #你的昵称
  icp:  #icp备案

# 导航配置
nav:
  主页: #导航id要与下方页面配置相同
    url: / #输入 / 将会转换成页面锚点
  仓库:
    url: https://blog.nalex.top/ #可以输入外部url
  博客:
    url: /
  项目:
    url: /
  媒体:
    url: /

# 顶部可弹出通知
notice:
  enable: true #开关
  url: https://github.com/rootlexblog/Heoweb #通知链接
  text: 项目已开源，点击查看此项目 #通知内容

# 首屏
firstWarp:
  enable: true #开关
  title: 开源改变世界 #首屏标题 可使用 <br> 换行
  text: 努力为开源事业出一份力<br>为这个世界出一份力 #可使用 <br> 换行
  button: false #按钮输入false可关闭
  buttonUrl: / #按钮链接
  img: /img/avatar.webp

#页面设置
page:
  博客:
    type: warp #页面类型warp/item
    warp:
      bg: '' #页面背景，仅warp可以填写，当为空时输出默认
      title: 博客
      desc: 参考了Pix主题的个人博客
      buttonLeft: #左侧按钮
        text: 访问项目
        url: https://blog.nalex.top/
      buttonRight: #右侧按钮
        enable: true
        text: Pix主题
        url: https://pixit.cn/
      img: /img/boke.webp #图片
  项目:
    type: item
    item:
      title: 项目
      desc: 我参与开发和维护的一些项目
      list: #item项目列表
        TianliCdn: #项目名称
          img: /img/tianlicdn.webp #icon图片地址
          text: 一个强大的静态资源加速服务 #文字描述
          button: #按钮相关配置
            text: 访问
            url: https://cdn1.tianli0.top/
        HeoWeb:
          img: /img/heo.png
          text: 基于Heo的主页开发的Hexo主题
          button:
            text: Github
            url: https://github.com/rootlexblog/Heoweb
        Kenny:
          img: /img/kenny.png
          text: 一个基于Tony开发的Hugo主题
          button:
            text: Github
            url: https://github.com/Kindle-deep/hugo-theme-Kenny
  Cdn:
    type: warp #页面类型warp/item
    warp:
      bg: "linear-gradient(45deg, #ff9a9e 0%, #fad0c4 99%, #fad0c4 100%)" #页面背景颜色，仅warp可以填写，当为空时输出默认
      title: TianliCdn
      desc: 一个强大且免费的静态资源加速服务
      buttonLeft: #左侧按钮
        text: 访问
        url: https://cdn1.tianli0.top/
      buttonRight: #右侧按钮
        enable: false
        text: Pix主题
        url: https://pixit.cn/
      img: /img/cdn.png #图片
  媒体:
    type: item
    item:
      title: 联系我
      desc: 您可以通过一下方式找到我
      list: #item项目列表
        Github: #项目名称
          img: /img/github.png #icon图片地址
          text: 全球最大的同性交友平台 #文字描述
          button: #按钮相关配置
            text: 访问
            url: https://github.com/rootlexblog
        网站:
          img: /img/avatar.webp
          text: 通过网站评论与我联系
          button:
            text: 访问
            url: https://blog.nalex.top/

extends: # 插入额外代码 如：统计，广告等
  head: # 在head中插入
    - <script></script>
  body: # 在body中插入

